In [6]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
vektor3 = np.array([7, 8, 9])

# Susun/stack vektor menjadi matrix kolom
A = np.column_stack((vector1, vector2, vektor3))

print(A)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
# Jika Dicari dengan Rank
# Hitung rank
rank = np.linalg.matrix_rank(A)

# Jika rank dari matrix A = n (jumlah vektor) maka vektor vektor tersebut independent jika tidak maka dependent
print(f"Rank\t:{rank}\nKolom\t:{A.shape[1]}\n")
if (rank == A.shape[1]):
    print("vektor-vektor ini independen")
else:
    print("vektor vektor ini dependen")

Rank	:2
Kolom	:3

vektor vektor ini dependen


In [13]:
# Jika dicari dengan Determinan
# Dengan syarat bahwa kolom dan baris pada matrix harus sama
if A.shape[0] == A.shape[1]:
    # Hitung Determinan
    determinan = np.linalg.det(A)
    print(determinan)

    # Jika determinan != 0 vektor vektor tersebut independen
    if determinan != 0:
        print("vektor vektor ini independen")
    else:
        print("vektor vektor ini dependen")
else:
    print("matrix tidak persegi, gunakan metode rank")

0.0
vektor vektor ini dependen
